const {test,expect}=require('@playwright/test');

test('customer contribution is source-tied, selectable, and laptop-fit',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1024,height:720});
  await page.goto('/#view=profitability&page=0');
  await expect.poll(()=>page.evaluate(()=>reportState.pages.length)).toBeGreaterThan(3);
  const index=await page.evaluate(()=>reportState.pages.findIndex(item=>item.title==='Customer profitability'));
  expect(index).toBeGreaterThan(0);
  await page.goto(`/#view=profitability&page=${index}`);
  await expect(page.locator('.ccv-board')).toBeVisible();
  const source=await page.evaluate(()=>data.customer_profitability);
  await expect(page.locator('.ccv-row')).toHaveCount(Math.min(8,source.length));
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(await page.evaluate(()=>document.querySelector('.ccv-board').getBoundingClientRect().bottom<=document.querySelector('#content').getBoundingClientRect().bottom+1)).toBe(true);
  expect(await page.evaluate(()=>document.querySelector('.ccv-source').getBoundingClientRect().bottom<=document.querySelector('.ccv-board').getBoundingClientRect().bottom-2)).toBe(true);
  const expected=source.reduce((sum,row)=>sum+Number(row.operating_contribution),0);
  for(const row of source)expect(Math.abs(row.gross_profit-row.opex-row.operating_contribution)).toBeLessThan(.01);
  await expect(page.locator('.ccv-summary strong').first()).toHaveText(`€${(expected/1e6).toFixed(2)}m`);
  await page.screenshot({path:'test-results/customer-contribution-desktop.png',fullPage:true});
  await page.locator('.ccv-row').nth(1).click();
  await expect(page.locator('.ccv-row').nth(1)).toHaveAttribute('aria-pressed','true');
  const selected=await page.evaluate(()=>{const option=document.querySelector('[data-cc-select]').selectedOptions[0];return data.customer_profitability.find(row=>option.textContent.includes(row.customer_name)&&option.textContent.includes(row.entity))});
  await page.locator('[data-cc-evidence]').click();
  await expect(page.locator('#reportDialog')).toBeVisible();
  await expect(page.locator('#reportDialogBody')).toContainText(selected.customer);
  await expect(page.locator('#reportDialogBody')).toContainText('Gross profit − allocated OPEX');
  expect(Math.abs(selected.gross_profit-selected.opex-selected.operating_contribution)).toBeLessThan(.01);
  expect(errors).toEqual([]);
  await page.locator('#reportDialogClose').click();
  await page.locator('[data-cc-select]').selectOption({index:source.length-1});
  await expect(page.locator('.ccv-identity strong')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/customer-contribution-mobile.png',fullPage:true});
  await page.locator('.ccv-source').scrollIntoViewIfNeeded();
  await expect(page.locator('.ccv-source')).toBeInViewport();
  await page.goto(`/#view=profitability&page=${index}&entity=US01&division=Hardware`);
  await expect(page.locator('.ccv-board')).toBeVisible();
  const scoped=source.filter(row=>row.entity==='US01'&&row.division==='Hardware');
  await expect(page.locator('.ccv-summary strong').last()).toHaveText(String(scoped.length));
  await expect(page.locator('.ccv-row')).toHaveCount(Math.min(8,scoped.length));
});
