const {test,expect}=require('@playwright/test');

test('SKU watch exposes exact cost bridge and source rounding without clipping',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1024,height:720});
  await page.goto('/#view=profitability&page=0');
  await expect.poll(()=>page.evaluate(()=>reportState.pages.length)).toBeGreaterThan(3);
  const index=await page.evaluate(()=>reportState.pages.findIndex(item=>item.title==='SKU profitability'));
  expect(index).toBeGreaterThan(0);
  expect(await page.evaluate(()=>reportState.pages[4].html.includes('data-contribution="products"'))).toBe(true);
  await page.goto(`/#view=profitability&page=${index}`);
  await expect(page.locator('.spw-board')).toBeVisible();
  await expect(page.locator('.spw-row')).toHaveCount(8);
  await expect(page.locator('.spw-summary strong').nth(0)).toHaveText('220');
  await expect(page.locator('.spw-summary strong').nth(1)).toHaveText('0');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(await page.evaluate(()=>document.querySelector('.spw-source').getBoundingClientRect().bottom<=document.querySelector('.spw-board').getBoundingClientRect().bottom-2)).toBe(true);
  await page.screenshot({path:'test-results/sku-watch-desktop.png',fullPage:true});
  await page.locator('.spw-row').nth(1).click();
  await expect(page.locator('.spw-row').nth(1)).toHaveAttribute('aria-pressed','true');
  await page.locator('[data-spw-evidence]').click();
  await expect(page.locator('#reportDialogBody')).toContainText('MC source rounding residual');
  await expect(page.locator('#reportDialogBody')).toContainText('GP source rounding residual');
  await expect(page.locator('#reportDialogBody')).toContainText('no balancing adjustment');
  await page.locator('#reportDialogClose').click();
  await page.locator('[data-spw-catalog]').click();
  await expect(page.locator('#reportDialog')).toContainText('Catalog structure');
  await expect(page.locator('#reportDialogBody')).toContainText('product_catalog');
  await page.locator('#reportDialogClose').click();
  await page.locator('[data-spw-select]').selectOption({index:219});
  await expect(page.locator('.spw-identity strong')).toBeVisible();
  await page.goto(`/#view=profitability&page=${index}&division=Hardware`);
  await expect(page.locator('.spw-board')).toBeVisible();
  const hardware=await page.evaluate(()=>data.product_profitability.filter(row=>row.division==='Hardware').length);
  await expect(page.locator('.spw-summary strong').nth(0)).toHaveText(String(hardware));
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('.spw-source').scrollIntoViewIfNeeded();
  await expect(page.locator('.spw-source')).toBeInViewport();
  await page.screenshot({path:'test-results/sku-watch-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
});
