const {test,expect}=require('@playwright/test');

test('supplier spend and AP rank from the same selected source without fake overdue exposure',async({page})=>{
  await page.setViewportSize({width:1280,height:720});
  await page.goto('/#view=working-capital&page=0');
  await expect.poll(()=>page.evaluate(()=>reportState.pages.length)).toBeGreaterThan(7);
  const sections=await page.evaluate(()=>reportState.pages.map((item,index)=>({title:item.title,index})));
  const suppliers=sections.find(item=>item.title.includes('Supplier concentration'));
  expect(suppliers?.title).toContain('Supplier aging watchlist');
  await page.goto(`/#view=working-capital&page=${suppliers.index}`);
  await expect(page.locator('.sr-visual')).toHaveCount(2);
  await expect(page.locator('.sr-row')).toHaveCount(10);
  await expect(page.locator('#entityFilter').locator('..')).toBeVisible();
  await expect(page.locator('.wq-source')).toHaveCount(2);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/supplier-risk-desktop.png',fullPage:true});
  await page.locator('.wq-source').first().locator('summary').click();
  await expect(page.locator('.wq-source').first().locator('table')).toBeVisible();
  await page.goto(`/#view=working-capital&page=${suppliers.index}&entity=US01&division=Hardware`);
  await expect(page.locator('#reportContext')).toContainText('US01');
  await expect(page.locator('.sr-row').first().locator('.sr-caption span')).toContainText('US01 · Hardware');
  const maturity=sections.find(item=>item.title.includes('AP aging'));
  expect(maturity).toBeTruthy();
  await page.goto(`/#view=working-capital&page=${maturity.index}&entity=US01&division=Hardware`);
  await expect(page.locator('.wq-aging')).toBeVisible();
  await expect(page.locator('.wq-aging-legend>div')).toHaveCount(5);
  await expect(page.locator('.wq-aging-foot')).toContainText('Buckets reconcile');
  await expect(page.locator('.sr-trend')).toBeVisible();
  await expect(page.locator('#reportContext')).toContainText('Group');
  await page.screenshot({path:'test-results/supplier-ap-maturity-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(`/#view=working-capital&page=${suppliers.index}`);
  const regions=page.getByRole('navigation',{name:'Dashboard regions'});
  await expect(regions.getByRole('button')).toHaveCount(2);
  await regions.getByRole('button').nth(1).click();
  await expect(page.locator('.sr-visual').last()).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/supplier-risk-mobile.png',fullPage:true});
});
