const {test,expect}=require('@playwright/test');

test('asset-quality exposures and group aging have honest scope, visual evidence and mobile regions',async({page})=>{
  await page.setViewportSize({width:1280,height:720});
  await page.goto('/#view=working-capital&page=0');
  await expect.poll(()=>page.evaluate(()=>reportState.pages.length)).toBeGreaterThan(5);
  const sections=await page.evaluate(()=>reportState.pages.map((item,index)=>({title:item.title,index})));
  const exposure=sections.find(item=>item.title.includes('Expected credit loss exposure'));
  const aging=sections.find(item=>item.title.includes('AR aging')&&item.title.includes('Inventory aging'));
  expect(exposure?.title).toContain('Inventory provision exposure');
  expect(aging).toBeTruthy();

  await page.goto(`/#view=working-capital&page=${exposure.index}`);
  await expect(page.locator('.wq-ranked')).toHaveCount(2);
  await expect(page.locator('.wq-aging')).toHaveCount(0);
  await expect(page.locator('.wq-ranked').first().locator('.wq-rank')).toHaveCount(5);
  await expect(page.locator('.wq-source')).toHaveCount(2);
  await expect(page.locator('#entityFilter').locator('..')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/wc-asset-exposure-desktop.png',fullPage:true});
  await page.locator('.wq-source').first().locator('summary').click();
  await expect(page.locator('.wq-source').first().locator('table')).toBeVisible();
  await page.goto(`/#view=working-capital&page=${exposure.index}&entity=US01&division=Hardware`);
  await expect(page.locator('#reportContext')).toContainText('US01');
  await expect(page.locator('.wq-ranked')).toHaveCount(2);
  await expect(page.locator('.wq-ranked').first().locator('.wq-rank-caption span').first()).toContainText('US01 · Hardware');
  await page.setViewportSize({width:390,height:844});
  await page.goto(`/#view=working-capital&page=${exposure.index}`);
  let regions=page.getByRole('navigation',{name:'Dashboard regions'});
  await expect(regions.getByRole('button')).toHaveCount(2);
  await expect(page.locator('.wq-ranked').first()).toBeVisible();
  await regions.getByRole('button').nth(1).click();
  await expect(page.locator('.wq-ranked').last()).toBeVisible();
  await expect(page.locator('.wq-ranked').first()).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/wc-asset-exposure-mobile.png',fullPage:true});

  await page.setViewportSize({width:1280,height:720});
  await page.goto(`/#view=working-capital&page=${aging.index}&entity=US01&division=Hardware`);
  await expect(page.locator('#reportContext')).toContainText('Group / fixed report scope');
  await expect(page.locator('.wq-aging')).toHaveCount(2);
  await expect(page.locator('.wq-ranked')).toHaveCount(0);
  await expect(page.locator('.wq-aging-stack i')).toHaveCount(10);
  await expect(page.locator('.wq-trend polyline')).toHaveCount(2);
  await expect(page.locator('.wq-aging-foot').first()).toContainText('Buckets reconcile');
  await expect(page.locator('.wq-source')).toHaveCount(2);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/wc-asset-aging-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(`/#view=working-capital&page=${aging.index}&entity=US01&division=Hardware`);
  regions=page.getByRole('navigation',{name:'Dashboard regions'});
  await expect(regions.getByRole('button')).toHaveCount(2);
  await expect(page.locator('.wq-aging').first()).toBeVisible();
  await regions.getByRole('button').nth(1).click();
  await expect(page.locator('.wq-aging').last()).toBeVisible();
  await expect(page.locator('.wq-aging').first()).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:'test-results/wc-asset-aging-mobile.png',fullPage:true});
});
