const eur=new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1});
const pct=v=>Number.isFinite(v)?`${(v*100).toFixed(1)}%`:'-';
const num=(v,d=1)=>Number.isFinite(v)?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'-';
const safe=v=>v===null||v===undefined?'':String(v);
const views=[
['executive','Executive','Group performance, cash conversion and forward outlook.'],
['pnl','P&L','Management P&L across entity and division.'],
['margin','Margin Engine','Marginal contribution, gross profit and price-volume-mix.'],
['working-capital','Working Capital','Receivables, inventory, payables and cash conversion.'],
['cash-flow','Cash Flow','Operating cash generation, CAPEX and financing movements.'],
['balance-sheet','Balance Sheet','Connected assets, liabilities and equity.'],
['forecast','Forecast','Rolling scenarios, historical vintages and forecast bias.'],
['profitability','Profitability','Product and customer economics.'],
['intercompany','Intercompany','Cost-plus flows and consolidation mechanics.'],
['operations-capex','Operations & CAPEX','Factory utilization, investment and portfolio events.'],
['data-journey','Data Journey','How the synthetic enterprise becomes reconciled finance data.']
];
let data=null;
let state={view:'executive',entity:'all',division:'all'};

function signed(v){const n=Number(v)||0;return `<span class="${n>=0?'value-pos':'value-neg'}">${eur.format(n)}</span>`}
function kpi(label,value,note=''){return `<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div>${note?`<div class="kpi-note">${note}</div>`:''}</div>`}
function panel(title,sub,body,span='span-12'){return `<article class="panel ${span}"><div class="panel-head"><div><div class="panel-title">${title}</div>${sub?`<div class="panel-sub">${sub}</div>`:''}</div></div>${body}</article>`}
function table(rows,cols){if(!rows?.length)return '<div class="empty">No data available for this selection.</div>';return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th class="${c.num?'num':''}">${c.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td class="${c.num?'num':''}">${c.format?c.format(r[c.key],r):safe(r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function bars(rows,key,labelKey='month'){
  if(!rows?.length)return '<div class="empty">No data.</div>';
  const vals=rows.map(r=>Number(r[key])||0),max=Math.max(...vals.map(Math.abs),1);
  const ticks=new Set(Array.from({length:Math.min(5,rows.length)},(_,i)=>Math.round(i*(rows.length-1)/Math.max(1,Math.min(5,rows.length)-1))));
  return `<div class="chart">${rows.map((r,i)=>{
    const v=Number(r[key])||0,ht=Math.max(2,Math.abs(v)/max*210),label=safe(r[labelKey]);
    return `<div class="bar-wrap${ticks.has(i)?' mobile-tick':''}"><div class="bar ${i===rows.length-1?'highlight':''} ${v<0?'negative':''}" style="height:${ht}px" title="${label}: ${eur.format(v)}" role="img" aria-label="${label}: ${eur.format(v)}"></div><div class="bar-label">${label.length>5?label.slice(2):label}</div></div>`;
  }).join('')}</div>`;
}
function metricRows(rows){return rows.map(([l,v])=>`<div class="metric-row"><span>${l}</span><strong>${v}</strong></div>`).join('')}
function latest(rows){return rows?.length?rows[rows.length-1]:{}}
function previousYear(rows){return rows?.length>12?rows[rows.length-13]:null}
function filteredManagement(){let rows=data.management_detail||[];if(state.entity!=='all')rows=rows.filter(r=>r.entity===state.entity);if(state.division!=='all')rows=rows.filter(r=>r.division===state.division);return rows}
function aggregateManagement(){const out=new Map();for(const r of filteredManagement()){const x=out.get(r.month)||{month:r.month,revenue:0,marginal_contribution:0,gross_profit:0,opex:0,depreciation:0,ebit:0,net_income:0};for(const k of ['revenue','marginal_contribution','gross_profit','opex','depreciation','ebit','net_income'])x[k]+=Number(r[k])||0;out.set(r.month,x)}return [...out.values()].sort((a,b)=>a.month.localeCompare(b.month))}
function currentScopeDetail(){return filteredManagement().filter(r=>r.month===data.meta.end_month)}
function currentDivisionSummary(){const map=new Map();for(const r of currentScopeDetail()){const x=map.get(r.division)||{division:r.division,revenue:0,marginal_contribution:0,gross_profit:0,ebit:0};for(const k of ['revenue','marginal_contribution','gross_profit','ebit'])x[k]+=Number(r[k])||0;map.set(r.division,x)}return [...map.values()]}

function renderExecutive(){const rows=aggregateManagement(),l=latest(rows),py=previousYear(rows),wc=latest(data.working_capital||[]),cf=latest(data.cash_flow||[]),bs=latest(data.balance_sheet||[]),divs=currentDivisionSummary();const growth=py?.revenue?l.revenue/py.revenue-1:0;const comments=(data.commentary||[]).map(c=>`<div class="comment"><div class="comment-title">${c.headline}</div><div class="comment-detail">${c.detail}</div></div>`).join('');return `<div class="kpi-grid">${kpi('Revenue',eur.format(l.revenue||0),`${pct(growth)} YoY`)}${kpi('Gross margin',pct((l.gross_profit||0)/(l.revenue||1)))}${kpi('EBIT',eur.format(l.ebit||0),`${pct((l.ebit||0)/(l.revenue||1))} margin`)}${kpi('Group free cash flow',eur.format(cf.free_cash_flow||0),'Consolidated · not filtered')}${kpi('Group net working capital',eur.format(wc.net_working_capital||0),`Consolidated · DSO ${num(wc.dso,0)} days`)}</div><div class="panel-grid">${panel('Revenue trend','Selected scope, trailing 24 months',bars(rows.slice(-24),'revenue'),'span-8')}${panel('Group management commentary','Consolidated commentary · not filtered',`<div class="commentary">${comments||'<div class="empty">No commentary.</div>'}</div>`,'span-4')}${panel('Division performance','Current close',table(divs,[{key:'division',label:'Division'},{key:'revenue',label:'Revenue',num:true,format:v=>eur.format(v)},{key:'gross_profit',label:'Gross profit',num:true,format:v=>eur.format(v)},{key:'ebit',label:'EBIT',num:true,format:v=>signed(v)}]),'span-7')}${panel('Financial position','Latest consolidated close',metricRows([['Cash',eur.format(bs.cash||0)],['Inventory',eur.format(bs.inventory||0)],['Trade receivables',eur.format(bs.trade_receivables||0)],['Trade payables',eur.format(bs.trade_payables||0)],['Debt',eur.format(bs.debt||0)],['Equity',eur.format(bs.equity||0)]]),'span-5')}</div>`}
function renderPnl(){const rows=aggregateManagement(),l=latest(rows),detail=currentScopeDetail();return `<div class="kpi-grid">${kpi('Revenue',eur.format(l.revenue||0))}${kpi('Marginal contribution',eur.format(l.marginal_contribution||0),pct((l.marginal_contribution||0)/(l.revenue||1)))}${kpi('Gross profit',eur.format(l.gross_profit||0),pct((l.gross_profit||0)/(l.revenue||1)))}${kpi('OPEX',eur.format(l.opex||0),pct((l.opex||0)/(l.revenue||1)))}${kpi('EBIT',eur.format(l.ebit||0),pct((l.ebit||0)/(l.revenue||1)))}</div><div class="panel-grid">${panel('Monthly EBIT','Selected scope',bars(rows.slice(-24),'ebit'),'span-7')}${panel('Current month P&L','Management view',metricRows([['Revenue',eur.format(l.revenue||0)],['Variable costs',eur.format((l.revenue||0)-(l.marginal_contribution||0))],['Marginal contribution',eur.format(l.marginal_contribution||0)],['Fixed production cost',eur.format((l.marginal_contribution||0)-(l.gross_profit||0))],['Gross profit',eur.format(l.gross_profit||0)],['OPEX',eur.format(l.opex||0)],['Depreciation',eur.format(l.depreciation||0)],['EBIT',signed(l.ebit||0)],['Net income',signed(l.net_income||0)]]),'span-5')}${panel('Entity and division detail','Current close',table(detail,[{key:'entity',label:'Entity'},{key:'division',label:'Division'},{key:'revenue',label:'Revenue',num:true,format:v=>eur.format(v)},{key:'marginal_contribution',label:'MC',num:true,format:v=>eur.format(v)},{key:'gross_profit',label:'Gross profit',num:true,format:v=>eur.format(v)},{key:'ebit',label:'EBIT',num:true,format:v=>signed(v)}]),'span-12')}</div>`}
function renderMargin(){const pvm=data.pvm||[],div=currentDivisionSummary();return `<div class="kpi-grid">${div.map(d=>kpi(`${d.division} GM`,pct((d.gross_profit||0)/(d.revenue||1)),`MC ${pct((d.marginal_contribution||0)/(d.revenue||1))}`)).join('')}</div><div class="panel-grid">${panel('Price / Volume / Mix','Revenue bridge versus prior year',table(pvm,[{key:'division',label:'Division'},{key:'revenue_change',label:'Revenue delta',num:true,format:v=>signed(v)},{key:'price_effect',label:'Price',num:true,format:v=>signed(v)},{key:'volume_effect',label:'Volume',num:true,format:v=>signed(v)},{key:'mix_effect',label:'Mix',num:true,format:v=>signed(v)}]),'span-7')}${panel('Margin hierarchy','Current selected scope',`<div class="waterfall">${['revenue','marginal_contribution','gross_profit','ebit'].map(k=>{const v=div.reduce((s,r)=>s+(Number(r[k])||0),0);return `<div class="wf"><div class="wf-label">${k.replaceAll('_',' ')}</div><div class="wf-value">${eur.format(v)}</div></div>`}).join('')}</div>`,'span-5')}</div>`}
function renderWC(){const rows=data.working_capital||[],l=latest(rows);return `<div class="kpi-grid">${kpi('Trade receivables',eur.format(l.trade_receivables||0),`DSO ${num(l.dso,0)}`)}${kpi('Inventory',eur.format(l.inventory||0),`DIO ${num(l.dio,0)}`)}${kpi('Trade payables',eur.format(l.trade_payables||0),`DPO ${num(l.dpo,0)}`)}${kpi('Net working capital',eur.format(l.net_working_capital||0))}${kpi('Cash conversion cycle',`${num((l.dso||0)+(l.dio||0)-(l.dpo||0),0)} days`)}</div><div class="panel-grid">${panel('Net working capital trend','Receivables + Inventory - Payables',bars(rows.slice(-24),'net_working_capital'),'span-8')}${panel('Efficiency ratios','Latest month',metricRows([['DSO',`${num(l.dso,1)} days`],['DIO',`${num(l.dio,1)} days`],['DPO',`${num(l.dpo,1)} days`],['Cash conversion cycle',`${num((l.dso||0)+(l.dio||0)-(l.dpo||0),1)} days`]]),'span-4')}</div>`}
function renderCash(){const rows=data.cash_flow||[],l=latest(rows);return `<div class="kpi-grid">${kpi('Operating cash flow',eur.format(l.operating_cash_flow||0))}${kpi('Investing cash flow',eur.format(l.investing_cash_flow||0))}${kpi('Financing cash flow',eur.format(l.financing_cash_flow||0))}${kpi('Free cash flow',eur.format(l.free_cash_flow||0))}${kpi('Net cash movement',eur.format(l.net_cash_movement||0))}</div><div class="panel-grid">${panel('Free cash flow','Monthly cash conversion',bars(rows.slice(-24),'free_cash_flow'),'span-8')}${panel('Latest cash bridge','Current month',metricRows([['Operating cash flow',signed(l.operating_cash_flow||0)],['Investing cash flow',signed(l.investing_cash_flow||0)],['Financing cash flow',signed(l.financing_cash_flow||0)],['Net cash movement',signed(l.net_cash_movement||0)]]),'span-4')}</div>`}
function renderBS(){const rows=data.balance_sheet||[],l=latest(rows);return `<div class="kpi-grid">${kpi('Assets',eur.format(l.assets||0))}${kpi('Liabilities',eur.format(l.liabilities||0))}${kpi('Equity',eur.format(l.equity||0))}${kpi('Cash',eur.format(l.cash||0))}${kpi('Balance check',eur.format(l.balance_check||0),Math.abs(l.balance_check||0)<.1?'Reconciled':'Review')}</div><div class="panel-grid">${panel('Asset structure','Latest consolidated balance sheet',metricRows([['Cash',eur.format(l.cash||0)],['Trade receivables',eur.format(l.trade_receivables||0)],['Inventory',eur.format(l.inventory||0)],['PPE gross',eur.format(l.ppe_gross||0)],['CIP',eur.format(l.cip||0)],['Accumulated depreciation',eur.format(l.accumulated_depreciation||0)]]),'span-6')}${panel('Funding structure','Latest consolidated balance sheet',metricRows([['Trade payables',eur.format(l.trade_payables||0)],['Tax payable',eur.format(l.tax_payable||0)],['Debt',eur.format(l.debt||0)],['Share capital',eur.format(l.share_capital||0)],['Retained earnings',eur.format(l.retained_earnings||0)]]),'span-6')}${panel('Total assets trend','Connected to operating and financing activity',bars(rows.slice(-24),'assets'),'span-12')}</div>`}
function renderForecast(){const all=data.forecast||[],base=all.filter(r=>r.scenario==='Base'),up=all.filter(r=>r.scenario==='Upside'),down=all.filter(r=>r.scenario==='Downside'),acc=data.forecast_accuracy||[],next=base[0]||{};const sum12=rows=>rows.filter(r=>r.horizon_month<=12).reduce((s,r)=>s+(Number(r.revenue_forecast)||0),0);return `<div class="kpi-grid">${kpi('Current vintage',data.meta.end_month)}${kpi('Forecast horizon',`${base.length} months`)}${kpi('Next month revenue',eur.format(next.revenue_forecast||0))}${kpi('12M revenue',eur.format(sum12(base)))}${kpi('Scenarios','3','Base / Upside / Downside')}</div><div class="panel-grid">${panel('Base forecast','Revenue by forward month',bars(base,'revenue_forecast'),'span-8')}${panel('Scenario range','Next 12 months',metricRows([['Base',eur.format(sum12(base))],['Upside',eur.format(sum12(up))],['Downside',eur.format(sum12(down))]]),'span-4')}${panel('Forecast accuracy','Historical vintages',table(acc,[{key:'horizon_month',label:'Horizon',format:v=>`${v}M`},{key:'mape',label:'MAPE',num:true,format:v=>pct(v)},{key:'bias',label:'Bias',num:true,format:v=>pct(v)},{key:'observations',label:'Observations',num:true}]),'span-12')}</div>`}
function renderProfitability(){const prod=data.product_profitability||[],cust=data.customer_profitability||[];return `<div class="panel-grid">${panel('Product profitability','Lowest operating contribution over trailing 12 months',table(prod,[{key:'division',label:'Division'},{key:'name',label:'Product'},{key:'revenue',label:'Revenue',num:true,format:v=>eur.format(v)},{key:'gross_margin_pct',label:'GM',num:true,format:v=>pct(v)},{key:'mc_pct',label:'MC',num:true,format:v=>pct(v)},{key:'operating_contribution',label:'Operating contribution',num:true,format:v=>signed(v)}]),'span-6')}${panel('Customer profitability','Lowest operating contribution over trailing 12 months',table(cust,[{key:'entity',label:'Entity'},{key:'customer_name',label:'Customer'},{key:'division',label:'Division'},{key:'revenue',label:'Revenue',num:true,format:v=>eur.format(v)},{key:'gross_margin_pct',label:'GM',num:true,format:v=>pct(v)},{key:'operating_contribution',label:'Operating contribution',num:true,format:v=>signed(v)}]),'span-6')}</div>`}
function renderIC(){const rows=data.intercompany||[],l=latest(rows);return `<div class="kpi-grid">${kpi('Intercompany sales',eur.format(l.intercompany_sales||0))}${kpi('Manufacturing cost',eur.format(l.manufacturing_cost||0))}${kpi('Transfer pricing markup',eur.format(l.transfer_pricing_markup||0))}${kpi('Markup rate',pct((l.transfer_pricing_markup||0)/(l.manufacturing_cost||1)))}${kpi('Consolidation','Eliminated','IC P&L and balances')}</div><div class="panel-grid">${panel('Intercompany flow','Manufacturing transfer value',bars(rows.slice(-24),'intercompany_sales'),'span-8')}${panel('Consolidation logic','Group reporting',`<div class="section-note">Factory entities sell to commercial entities using cost plus. Intercompany AR and AP settle through the ledger. Revenue, COGS and reciprocal balances are eliminated on consolidation. Unrealized transfer-pricing profit embedded in closing inventory is removed and released only when the inventory is sold externally.</div>`,'span-4')}</div>`}
function capexSummary(){const map=new Map();for(const r of data.capex||[]){const x=map.get(r.project)||{project:r.project,project_name:r.project_name,entity:r.entity,division:r.division,go_live:r.go_live,useful_life_months:r.useful_life_months,capacity_increase_pct:r.capacity_increase_pct,spend:0,last_month:r.month};x.spend+=Number(r.amount)||0;if(r.month>x.last_month)x.last_month=r.month;map.set(r.project,x)}return [...map.values()].map(x=>({...x,status:data.meta.end_month>=x.go_live?'Live':'In progress'}))}
function renderOps(){const factory=(data.factory||[]).filter(r=>r.month===data.meta.end_month),capex=capexSummary(),events=data.portfolio_events||[];return `<div class="panel-grid">${panel('Factory utilization','Latest month',table(factory,[{key:'factory',label:'Factory'},{key:'factory_name',label:'Site'},{key:'capacity_units',label:'Capacity',num:true,format:v=>num(v,0)},{key:'produced_units',label:'Production',num:true,format:v=>num(v,0)},{key:'utilization',label:'Utilization',num:true,format:v=>pct(v)},{key:'capacity_increase_pct',label:'Added capacity',num:true,format:v=>pct(v)}]),'span-6')}${panel('CAPEX portfolio','Project spend and go-live',table(capex,[{key:'project',label:'Project'},{key:'project_name',label:'Project name'},{key:'entity',label:'Entity'},{key:'spend',label:'Spend',num:true,format:v=>eur.format(v)},{key:'go_live',label:'Go-live'},{key:'status',label:'Status'}]),'span-6')}${panel('Portfolio decisions','Rule-based product lifecycle events',table(events,[{key:'month',label:'Decision month'},{key:'division',label:'Division'},{key:'product',label:'Product'},{key:'event',label:'Event'},{key:'effective_month',label:'Effective'},{key:'reason',label:'Reason'}]),'span-12')}</div>`}
function renderJourney(){const v=data.validation||{},checks=Object.entries(v).filter(([k])=>k!=='passed'),sources=data.sources||{};return `<div class="panel-grid">${panel('End-to-end finance pipeline','One causal chain',`<div class="flow">${['Public macro drivers','Business drivers','Operating transactions','Double-entry ledger','Legal entities','Consolidation','Financial statements','Rolling forecast','CFO analytics'].map(x=>`<div class="flow-step">${x}</div>`).join('')}</div>`,'span-12')}${panel('Release controls',v.passed?'All controls passed':'Control failure',`<div class="status-grid">${checks.map(([k,val])=>`<div class="status-item"><strong>${k.replaceAll('_',' ')}</strong><span class="${Number(val)===0?'good':''}">${safe(val)}</span></div>`).join('')}</div>`,'span-7')}${panel('Data sources','Live where useful, deterministic where required',`<div class="source-card"><strong>FX</strong>${safe(sources.fx?.preferred_source)}<br>Fallback: ${safe(sources.fx?.fallback)}<br>Live rows: ${safe(sources.fx?.live_rows)}</div><div class="source-card" style="margin-top:8px"><strong>Economic drivers</strong>${safe(sources.economic_drivers?.current)}<br>Planned: ${(sources.economic_drivers?.planned||[]).join(', ')}</div>`,'span-5')}${panel('Design rule','Why the statements reconcile',`<div class="section-note">The dashboard never generates P&L, Balance Sheet and Cash Flow independently. Economic activity creates balanced journal entries first. Every downstream statement is rebuilt from that ledger, and the monthly close is rejected when reconciliation controls exceed tolerance.</div>`,'span-12')}</div>`}

const renderers={executive:renderExecutive,pnl:renderPnl,margin:renderMargin,'working-capital':renderWC,'cash-flow':renderCash,'balance-sheet':renderBS,forecast:renderForecast,profitability:renderProfitability,intercompany:renderIC,'operations-capex':renderOps,'data-journey':renderJourney};
function render(){const cfg=views.find(v=>v[0]===state.view)||views[0];document.getElementById('viewTitle').textContent=cfg[1];document.getElementById('viewSubtitle').textContent=cfg[2];document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));document.getElementById('content').innerHTML=(renderers[state.view]||renderExecutive)();location.hash=`view=${state.view}`}
function setupNav(){document.getElementById('nav').innerHTML=views.map(v=>`<button data-view="${v[0]}">${v[1]}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render()}))}
function setupFilters(){const m=data.management_detail||[],entities=[...new Set(m.map(r=>r.entity))].sort(),divisions=[...new Set(m.map(r=>r.division))].sort(),ef=document.getElementById('entityFilter'),df=document.getElementById('divisionFilter');ef.innerHTML='<option value="all">All entities</option>'+entities.map(x=>`<option>${x}</option>`).join('');df.innerHTML='<option value="all">All divisions</option>'+divisions.map(x=>`<option>${x}</option>`).join('');ef.addEventListener('change',()=>{state.entity=ef.value;render()});df.addEventListener('change',()=>{state.division=df.value;render()})}
async function init(){setupNav();try{data=await fetch('data/dashboard.json?v=0.20.0',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()});const hash=new URLSearchParams(location.hash.replace(/^#/,'')),hv=hash.get('view');if(views.some(v=>v[0]===hv))state.view=hv;setupFilters();document.getElementById('closeStatus').textContent=`Closed through ${data.meta.end_month} | ${data.validation?.passed?'Controls passed':'Controls failed'}`;render()}catch(err){document.getElementById('closeStatus').textContent='Dataset unavailable';document.getElementById('content').innerHTML=`<div class="panel"><div class="panel-title">Dashboard dataset not available</div><p class="section-note">${safe(err)}</p></div>`}}
