/* Guided, evidence-linked explanation of the end-to-end monthly close. */
(function(root){
  const stages=[
    {title:'Drivers',outcome:'Business activity captured',summary:'The close begins with public macro observations and deterministic operating assumptions. Those drivers shape demand, pricing, payroll, production, working capital and funding before any accounting output exists.',inputs:['Official macro observations','Product and commercial assumptions','Workforce and factory capacity'],outputs:['Monthly operating drivers','Traceable source lineage','Reproducible close inputs'],controls:[['macro_lineage_missing_rows','Complete macro lineage','macro_lineage'],['macro_lineage_duplicate_rows','Unique driver observations','macro_lineage'],['sensitivity_detail_summary_max_gap','Sensitivity detail tie-out','financial_sensitivity_detail']],evidence:[['Business drivers','business-drivers','Operating volumes, prices and capacity'],['Macro & sensitivities','macro-sensitivities','Official sources, fallbacks and scenario shocks'],['Data journey','data-journey','Published source lineage']]},
    {title:'Transactions',outcome:'Valid, complete and classified',summary:'Operating events become invoices, supplier accruals, payroll, CAPEX, treasury movements and foreign-currency documents. Operational grains remain asymmetric by business model, while every event keeps a route into finance.',inputs:['Orders, subscriptions and events','Purchasing, payroll and CAPEX','Treasury and FX documents'],outputs:['Customer and supplier subledgers','Asset and workforce schedules','Classified accounting events'],controls:[['contract_ar_subledger_max_gap','Contract AR tie-out','contract_entity_summary'],['ap_subledger_max_gap','Supplier AP tie-out','ap_supplier_aging'],['workforce_payroll_journal_max_gap','Payroll-to-journal tie-out','workforce_detail']],evidence:[['Working capital','working-capital','Customer, inventory and supplier schedules'],['Operations & CAPEX','operations-capex','Factories, projects and asset events'],['FX & translation','fx','Open documents and remeasurement']]},
    {title:'Double-entry ledger',outcome:'Balanced and reconciled',summary:'Every economic event is translated into balanced journal lines. The ledger—not disconnected dashboard totals—is the accounting source from which trial balances and statements are rebuilt.',inputs:['Classified operating events','Chart-of-accounts rules','Entity and counterparty master data'],outputs:['Balanced journal','Entity trial balances','Audit-ready source lineage'],controls:[['journal_balance_max_gap','Journal debit / credit balance','journal.csv.gz'],['trial_balance_gap','Trial balance reconciliation','trial_balance.csv'],['factory_absorption_journal_max_gap','Factory absorption posting','factory_absorption']],evidence:[['Data journey','data-journey','Pipeline and release controls'],['P&L','pnl','Ledger-derived performance'],['Balance sheet','balance-sheet','Ledger-derived financial position']]},
    {title:'Legal close',outcome:'Books closed and reconciled',summary:'Period-end routines complete accruals, provisions, asset valuation, contract liabilities, working-capital schedules and legal statements. Exceptions remain visible; differences are never hidden with balancing plugs.',inputs:['Posted journal and subledgers','Provision and ageing policies','Period-end close routines'],outputs:['Closed legal trial balances','Legal financial statements','Reconciled subledger schedules'],controls:[['legal_balance_sheet_max_gap','Legal balance-sheet equation','balance_sheet'],['credit_loss_allowance_max_gap','Credit-loss allowance tie-out','credit_loss_detail'],['inventory_provision_max_gap','Inventory provision tie-out','inventory_provision_detail']],evidence:[['Balance sheet','balance-sheet','Assets, liabilities and equity'],['Working capital','working-capital','Gross-to-net schedules and ageing'],['P&L','pnl','Revenue-to-EBIT statement']]},
    {title:'Consolidation & FX',outcome:'Group view prepared',summary:'Legal entities are translated from functional currency, reciprocal intercompany balances and results are eliminated, CTA is kept separate from transaction FX, and unrealised profit in inventory is reserved until external sale.',inputs:['Legal entity trial balances','Functional-currency mirrors','Intercompany counterparties'],outputs:['EUR group consolidation','Elimination and reserve bridges','CTA and FX analytical layers'],controls:[['legal_ic_ar_ap_max_mismatch','Reciprocal IC matching','intercompany'],['consolidation_revenue_max_gap','Revenue consolidation bridge','consolidation_bridge'],['fx_translation_balance_max_gap','FX translation balance','fx_translation']],evidence:[['Intercompany','intercompany','Cost-plus flows and eliminations'],['FX & translation','fx','Translation, CTA and transaction FX'],['Balance sheet','balance-sheet','Consolidated group position']]},
    {title:'Financial statements',outcome:'Disclosures ready for review',summary:'P&L, Balance Sheet and Cash Flow are derived from the same close. Working capital, CAPEX, financing and retained earnings therefore remain causally connected and can be explained from statement back to source.',inputs:['Consolidated trial balance','Cash and non-cash classifications','Statement mapping rules'],outputs:['P&L and margins','Balance Sheet','Direct and indirect cash views'],controls:[['consolidated_balance_sheet_max_gap','Consolidated balance-sheet equation','balance_sheet'],['cash_flow_reconciliation_max_gap','Cash-flow reconciliation','cash_flow'],['consolidation_ebit_max_gap','EBIT consolidation bridge','consolidation_bridge']],evidence:[['P&L','pnl','Revenue, contribution, gross profit and EBIT'],['Cash flow','cash-flow','Operating, investing and financing cash'],['Balance sheet','balance-sheet','Connected closing balances']]},
    {title:'Forecast & review',outcome:'Outlook updated with actuals',summary:'The closed actual becomes the new forecast anchor. Base, Upside and Downside scenarios roll forward the three statements, while the performance review identifies material variance, bias and cash-conversion priorities.',inputs:['Validated actual close','Frozen budget and prior forecasts','Operational and macro drivers'],outputs:['18-month rolling forecast','Integrated three statements','Monthly performance review'],controls:[['forecast_lookahead_errors','Forecast horizon continuity','forecast'],['three_statement_balance_sheet_max_gap','Forecast balance-sheet equation','forecast_balance_sheet'],['performance_review_source_max_gap','Review-to-source tie-out','performance_review']],evidence:[['Plan & forecast','forecast','Scenarios, vintages and bias'],['Performance review','performance-review','Materiality and variance evidence'],['Macro & sensitivities','macro-sensitivities','Controlled what-if analysis']]},
    {title:'Actions & benefits',outcome:'Insights converted into outcomes',summary:'Material review findings become owned actions with priority, due date, status and evidence. Approved plans change future operating drivers through a controlled ramp; benefits are measured against their original source.',inputs:['Material review findings','Owners and governance rules','Approved execution plans'],outputs:['Persistent action lifecycle','Forecast and actual benefits','Evidence-backed management response'],controls:[['management_action_orphans','No orphan actions','management_actions'],['management_lifecycle_duplicate_ids','Unique lifecycle records','management_action_history'],['action_execution_actual_impact_missing','Complete actual-impact evidence','management_action_actual_impact']],evidence:[['Action execution','action-execution','Owner, status, plan and realised impact'],['Performance review','performance-review','Original management evidence'],['Executive overview','executive','Decision narrative and priorities']]}
  ];
  const competencies=[
    ['Accounting','Post and close subledgers; prepare journals','Trial balance, journals, reconciliations','Balanced journal and legal BS','Accurate financial records'],
    ['Controlling','Validate P&L, margins and allocations','Variance, profitability, WC and factory schedules','Source-to-report reconciliation','Reliable performance explanation'],
    ['Treasury','Control cash, debt, liquidity and interest','Cash pool, debt schedule, liquidity forecast','Cash roll-forward and covenant checks','Funding and capital decisions'],
    ['Consolidation','Translate entities and eliminate IC','FX schedules and consolidation bridges','IC matching, CTA and group BS','Group financial statements'],
    ['FP&A','Update forecast and analyse scenarios','Budget, forecast vintages and sensitivities','Three-statement identities and bias','Forward-looking decisions'],
    ['Governance','Run review and action lifecycle','Control manifest, reviews and action history','Release gate and evidence integrity','Accountability and audit readiness']
  ];
  let selected=0;
  const esc=value=>root.FinanceReport.escape(String(value??''));
  const icon='<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M6 4h8v12H6zM8 7h4M8 10h4M8 13h3"/></svg>';
  function passed(data,key){const value=data.validation?.[key];return typeof value==='number'?Math.abs(value)<0.1:value===0||value===false;}
  function route(view){state.view=view;reportState.page=0;render();}
  function shell(data){return `<article class="close-journey" data-close-journey><header class="cj-head"><div><p>Home / Close journey</p><h2>From business activity to management action</h2><span>A guided, evidence-linked tour of the ${esc(data.meta.end_month)} close</span></div><div><button id="cj-start">▶ Start guided tour</button><button id="cj-controls">View controls</button></div></header><div id="cj-stage"></div></article>`;}
  function stageHtml(data,index){const stage=stages[index],allPassed=stage.controls.every(control=>passed(data,control[0]));return `<nav class="cj-steps" aria-label="Monthly close journey">${stages.map((item,i)=>`<button data-cj-step="${i}" aria-current="${i===index?'step':'false'}"><b>${i+1}</b><strong>${esc(item.title)}</strong><span><i></i>${item.controls.every(control=>passed(data,control[0]))?'Passed':'Review'}</span><small>${esc(item.outcome)}</small></button>`).join('')}</nav><div class="cj-workspace"><section class="cj-explain"><h3>What happens</h3><p>${esc(stage.summary)}</p><div class="cj-io"><div><h4>Inputs</h4><ul>${stage.inputs.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div><div><h4>Outputs</h4><ul>${stage.outputs.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div></div></section><section class="cj-controls"><h3>How it is controlled</h3><p>Every claim below is evaluated by the published release gate.</p><table><thead><tr><th>Control</th><th>Status</th><th>Source dataset</th></tr></thead><tbody>${stage.controls.map(control=>`<tr><td>${esc(control[1])}</td><td class="${passed(data,control[0])?'favorable':'unfavorable'}">● ${passed(data,control[0])?'Passed':'Review'}</td><td>${esc(control[2])}</td></tr>`).join('')}</tbody></table><div class="cj-proof-chain"><span><small>Source</small><strong>${esc(stage.inputs[0])}</strong></span><i>→</i><span><small>Controlled process</small><strong>${esc(stage.title)}</strong></span><i>→</i><span class="final"><small>Outcome</small><strong>${esc(stage.outcome)}</strong></span></div></section><section class="cj-evidence"><h3>Where to prove it</h3><p>Follow the data from source to report. Each destination opens real published evidence.</p>${stage.evidence.map((item,i)=>`<button data-cj-view="${esc(item[1])}" class="cj-evidence-row">${icon}<span><strong>${esc(item[0])}</strong><small>${esc(item[2])}</small></span><i>›</i></button>`).join('')}<button id="cj-open-evidence">Open evidence</button></section></div><section class="cj-matrix"><header><h3>End-to-end competency map</h3><span>How each finance function contributes across the close journey.</span></header><table><thead><tr><th>Function</th><th>Process</th><th>Evidence</th><th>Key control</th><th>Decision output</th></tr></thead><tbody>${competencies.map(row=>`<tr>${row.map((cell,i)=>`<${i?'td':'th'}>${esc(cell)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></section><footer class="cj-guide"><span>Click any step to see what it does, how it is controlled and where to find the evidence.</span><div><strong>${index+1} of ${stages.length} · ${esc(stage.title)}</strong><button id="cj-prev" ${index===0?'disabled':''}>Previous</button><button id="cj-next" ${index===stages.length-1?'disabled':''}>Next</button></div></footer>`;}
  function mount(data){const host=document.getElementById('cj-stage');if(!host)return;const paint=()=>{host.innerHTML=stageHtml(data,selected);host.querySelectorAll('[data-cj-step]').forEach(button=>button.onclick=()=>{selected=Number(button.dataset.cjStep);paint();});host.querySelectorAll('[data-cj-view]').forEach(button=>button.onclick=()=>route(button.dataset.cjView));document.getElementById('cj-open-evidence').onclick=()=>route(stages[selected].evidence[0][1]);document.getElementById('cj-prev').onclick=()=>{selected=Math.max(0,selected-1);paint();};document.getElementById('cj-next').onclick=()=>{selected=Math.min(stages.length-1,selected+1);paint();};};paint();document.getElementById('cj-start').onclick=()=>{selected=0;paint();document.querySelector('[data-cj-step="0"]').focus();};document.getElementById('cj-controls').onclick=()=>route('data-journey');}
  root.CloseJourney={pages:data=>[{title:'Close journey',custom:true,policy:root.ReportContext.group,html:shell(data)}],mount,stages};
  if(typeof module!=='undefined'&&module.exports)module.exports=root.CloseJourney;
})(globalThis);
