/* Source-tied graphical income statement. No invented account allocations. */
(function(root){
  function rows(ac,py,M){
    const extend=row=>[...M.statement(row),{key:'below_ebit',label:'Net finance costs and tax',cost:true,value:M.finite(row.ebit)&&M.finite(row.net_income)?row.ebit-row.net_income:null},{key:'net_income',label:'Net income',total:true,value:row.net_income}];
    const previous=extend(py);let running=0;
    return extend(ac).map((r,i)=>{const start=r.total?0:running,end=r.total?r.value:M.finite(r.value)&&M.finite(running)?running-r.value:null;running=end;return {...r,start,end,prior:previous[i].value,change:M.variance(r.value,previous[i].value,r.cost?-1:1)};});
  }
  function render(ac,py,month,scope){
    const M=root.FinanceReport,esc=M.escape,items=rows(ac,py,M),max=Math.max(1,...items.flatMap(r=>[Math.abs(r.start||0),Math.abs(r.end||0)])),deltaMax=Math.max(1,...items.map(r=>Math.abs(r.change.delta||0))),pctMax=Math.max(.01,...items.map(r=>Math.abs(r.change.relative||0)));
    const amount=v=>M.finite(v)?(Math.abs(v)>=1e6?`${(v/1e6).toFixed(1)}M`:`${(v/1e3).toFixed(1)}K`):'—',signed=v=>M.finite(v)?`${v>0?'+':''}${amount(v)}`:'—';
    return `<article class="pnl-visual"><header><h2>Income statement · Actual vs prior year</h2><p>${esc(month)} · EUR million · ${esc(scope)} · Select a line for its calculation</p></header><div class="pnl-scroll" tabindex="0" role="region" aria-label="Graphical income statement; scroll to explore all columns"><div class="pnl-grid"><div class="pnl-heading"><span>Income statement</span><span>PY</span><span>AC · income bridge</span><span>Δ PY</span><span>Δ PY %</span></div>${items.map(r=>{const tone=r.change.favorable===true?'good':r.change.favorable===false?'bad':'neutral',left=50+Math.min(r.start||0,r.end||0)/max*42,width=Math.abs((r.end||0)-(r.start||0))/max*42;return `<button class="pnl-row ${r.total?'subtotal':''}" data-pnl-key="${r.key}" aria-label="${esc(r.label)}: actual ${amount(r.value)}, prior year ${amount(r.prior)}"><span>${r.total?'= ':'− '}${esc(r.label)}</span><span>${amount(r.prior)}</span><span class="pnl-track"><i style="left:${left}%;width:${width}%"></i><b>${amount(r.value)}</b></span><span class="pnl-delta ${tone}"><i style="left:${r.change.delta<0?50-Math.abs(r.change.delta)/deltaMax*45:50}%;width:${Math.abs(r.change.delta||0)/deltaMax*45}%"></i><b>${signed(r.change.delta)}</b></span><span class="pnl-percent ${tone}"><i style="left:${r.change.relative<0?50-Math.abs(r.change.relative)/pctMax*45:50}%;width:${Math.abs(r.change.relative||0)/pctMax*45}%"></i><b>${M.finite(r.change.relative)?`${r.change.relative>0?'+':''}${(r.change.relative*100).toFixed(1)}%`:'—'}</b></span></button>`;}).join('')}</div></div><p class="pnl-note">Green = favorable; red = unfavorable. Costs use lower-is-better. Net finance costs and tax are shown together because this operating dataset does not provide their separate allocation.</p></article>`;
  }
  const api={rows,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.PnlVisual=api;
})(globalThis);
